all:
	pdflatex poster && bibtex poster && pdflatex poster && bibtex poster

clean:
	rm -f poster.dvi poster.aux poster.bbl poster.log poster.lof poster.lot poster.toc poster.blg poster.pdf poster.out poster_defs.aux
