function bt_eval(h,s){try{return window.eval.apply(window,[h])}catch(x){s&&s(x)}}var bt_parameter=function(){var h;return function(s,x){var C=x||document;"undefined"===typeof h&&(h=new BrightTag.HTTP.URL(C.location.href));return h.param(s)}}();function bt_meta(h,s){for(var x,C=(s||document).getElementsByTagName("meta"),I=0,J=C.length;I<J;I++)if(x=C[I],x.getAttribute("name")===h)return x.getAttribute("content");return""}
function bt_cookie(h,s){return(new BrightTag.HTTP.Cookie(s||document)).get(h)||""}function bt_data(h,s){var x=BrightTag.instance||BrightTag.configuredSites()[0];return x?x.data(h,s):""}window.bt_data_escaped=bt_data;function bt_log(h){window.console&&console.log&&console.log("BrightTag: "+h)}var bt_handle_exception=bt_log;
window.BrightTag=function(h){function s(a,c){return Object.prototype.toString.call(a)==="[object "+c+"]"}function x(a){return a.replace(/^\s\s*/,"").replace(/\s\s*$/,"")}function C(a){return"\n//at-sourceURL=/BrightTag/"+a.replace(/\s+/g,"_")+".js"}function I(a,c){for(var d=0,b=this.length;d<b;d++)a.call(c,this[d],d,this)}function J(a,c,d){for(var b in a)a.hasOwnProperty(b)&&c.call(d,b,a[b],a)}function r(a,c,d){a&&(n.isArray(a)||a.length?O.call(a,c,d):n.isObject(a)&&J(a,c,d))}function v(a,c){J(c,
function(d,b){a[d]=b});return a}function la(a,c){var d=this.slice(),b=[];O.call(d,function(d,e){a.call(c,d,e,this)&&b.push(d)});return b}function S(a,c,d){return ma.call(n.isArray(a)?a:[a],c||function(a){return!!a},d)}function na(a,c){var d=this.slice(),b=Array(d.length);O.call(d,function(d,e){b[e]=a.call(c,d,e,this)});return b}function A(a,c){var d,b,f=n.isArray(a)?a:[a];d=0;for(b=f.length;d<b;d++)if(f[d]===c)return!0;return!1}function T(a){return!n.isString(a)?a:a.replace(/%/g,"%25").replace(/#/g,
"%23").replace(/&/g,"%26").replace(/'/g,"%27").replace(/;/g,"%3B").replace(/</g,"%3C").replace(/>/g,"%3E")}function U(a){for(var c=5381,d=0,b=a.length;d<b;)c=(c<<5)+c+a.charCodeAt(d++);return c.toString(36)}function V(a){function c(){}function d(a){var b=Array.prototype.slice.call(arguments,1);y.each(r,function(l){var d=[u].concat(b);(l[a]||c).apply(null,d)})}function b(){F=!0;P=D.length;d("engine:off")}function f(){F&&d("engine:on");F=!1;v=0;(D[P++]||b)()}function e(a,b){return{type:a,exception:b}}
function g(){d("block:finish");f()}function l(b,l){var d=a.createElement(b.tagName),c=y.extend(y.extend({},b.defaults),l||{});y.each(b.supported,function(a){n.isString(a)&&null!=c[a]?d[a]=c[a]:n.isObject(a)&&null!=c[a.option]&&a.setter(d,c[a.option])});return d}function m(b,c){var m=l(s.iframe,c);m.onerror=function(){d("block:error",e("iframe","Problem loading "+b))};d("block:start",b);m.src=b.toString();a.body.appendChild(m);g()}function k(a,b){var c=l(s.image,b);c.onerror=function(){d("block:error",
e("image","Problem loading "+a))};d("block:start",a);c.src=a.toString();g()}function t(b,c,m){var k=!1,t=l(s.script,m);t.onerror=function(){d("block:error",e("script","Problem loading "+b));k||g()};t.onload=t.onreadystatechange=function(){var a;if(!(a=k)){a:{switch(t.readyState){case void 0:case "loaded":case "complete":a=!0;break a}a=!1}a=!a}a||(k=!0,g())};d("block:start",b);b&&(t.src=b.toString());c&&(t.text=c);c=a.getElementsByTagName("script")[0];c.parentNode.insertBefore(t,c)}function p(a){var b=
Array.prototype.slice.call(arguments,1);return function(){a.apply(null,b)}}function h(b){return function(){try{if(d("block:start",b),n.isString(b)){var c=y.trim(b).replace(/^\x3c!--/,"").replace(/--\x3e$/,"");a.defaultView?a.defaultView.eval.call(window,c):a.parentWindow?a.parentWindow.execScript(c):d("block:error",e("wait","Could not evaluate wait block ["+c+"]"))}else b()}catch(l){d("block:error",e("wait",l))}finally{g()}}}function q(a){D.push(a);F&&f();return u}function w(a){D.splice(P+v++,0,a);
return u}var u=this,r=[],B={},F=!1,D=[],P=0,v=0,s={iframe:{tagName:"iframe",defaults:{frameborder:"0",height:"1px",scrolling:"no",width:"1px"},supported:[{option:"display",setter:function(a,b){a.style.display=b}},"frameborder","id","height","scrolling","width"]},image:{tagName:"img",defaults:{},supported:[{option:"display",setter:function(a,b){a.style.display=b}},"id",{option:"height",setter:function(a,b){a.setAttribute("height",b)}},{option:"width",setter:function(a,b){a.setAttribute("width",b)}}]},
script:{tagName:"script",defaults:{type:"text/javascript"},supported:["async","id","type"]}};u.run=function(){d("engine:on");f()};u.options=function(a){y.extend(B,a);return u};u.option=function(a){return B[a]};u.iframe=function(a,b){return q(p(m,a,b))};u.image=function(a,b){return q(p(k,a,b))};u.script=function(a,b,c){return q(p(t,a,b,c))};u.wait=function(a){return q(h(a))};u.preemptCss=function(a,b){return w(p(t,a,b))};u.preemptIframe=function(a,b){return w(p(t,a,b))};u.preemptImage=function(a,b){return w(p(t,
a,b))};u.preemptScript=function(a,b,c){return w(p(t,a,b,c))};u.preemptWait=function(a){return w(h(a))};u.listen=function(a){r.push(a);(a["engine:listen"]||c).apply(null,[u]);return u}}function W(a){function c(a){e.push(a);l&&!m&&b()}function d(a){a.run()}function b(){var a=e[g];a&&(g++,a.listen(k).run())}var f,e=[],g=0,l=!1,m=!1,k={"engine:on":function(){m=!0},"engine:off":function(){m=!1;b()}};f=c;this.alwaysQueue=function(){f=c};this.neverQueue=function(){f=d};this.push=function(a){f(a);return a};
this.run=function(){l=!0;b()};this.applyListener=function(a){var b,c;b=g;for(c=e.length;b<c;b++)e[b].listen(a)};this.toString=function(){return"Group[name="+a+"; working="+m+"; running="+l+"]"}}function X(a,c){return{"engine:listen":function(d){d.listen(new oa(a,c))}}}function Y(a){function c(a){return f[a]||(f[a]=new W(a))}function d(a){return b.addToGroup(a,b.newEngine())}var b=this,f={undefined:new W(void 0)},e=[];f.undefined.neverQueue();b.addGlobalListener=function(a){e.push(a);r(f,function(b,
c){c.applyListener(a)})};b.addToGroup=function(a,b){r(e,function(a){b.listen(a)});return c(a).push(b)};b.newEngine=function(){return new V(a)};b.group=function(a){return d(a)};b.listen=function(){return d().listen.apply(null,arguments)};b.iframe=function(){return d().iframe.apply(null,arguments)};b.image=function(){return d().image.apply(null,arguments)};b.script=function(){return d().script.apply(null,arguments)};b.wait=function(){return d().wait.apply(null,arguments)};b.run=function(a){c(a).run()};
b.alwaysQueue=function(a){c(a).alwaysQueue()};b.neverQueue=function(a){c(a).neverQueue()};b.setOptions=function(){return d()}}function Q(a){function c(a){var b,c;a=a.split(/; ?/);f={};for(var d=0,e=a.length;d<e;d++){c=a[d];b=c.indexOf("=");var p=f,h=c.slice(0,b);b=c.slice(b+1);b=unescape(b);p[h]=b}}function d(b,d,m){if(b){m=m||{};b=[b+"="+T(d||"")];if((d=m.expires)||0===d)n.isNumber(d)&&(d=(new Date(d)).toGMTString()),b.push("expires="+d);(d=m.path)&&b.push("path="+d);(d=m.domain)&&b.push("domain="+
d);!0===m.secure&&b.push("Secure");!0===m.httponly&&b.push("HttpOnly");m=b.join(";");if(m.length<e)a.cookie=m;else throw{name:"CookieTooLongError",message:"Cookie reached 4096 byte limit"};c(a.cookie)}}function b(a,b){d(a,"",v(b||{},{expires:1}))}var f={},e=4096;c(a.cookie||"");return{get:function(a){return f[a]},set:d,remove:b,findEach:function(a,b){for(var c in f)f.hasOwnProperty(c)&&c.match(a)&&b(c,f[c])},clear:function(a){var c=v({},f),d;for(d in c)b(d,a)}}}function Z(a){a=Q(a);var c=a.set,d=
a.remove;a.set=function(a,d,e){e=v(e||{},{path:"/"});0===e.expires&&(e.expires=+new Date("1/1/2038"));c(a,d,e)};a.remove=function(a,c){d(a,v(c||{},{path:"/"}))};a.purge=function(){};return a}function $(a,c){function d(a){a=a.expires;return 0!==a&&a<=+new Date}function b(b,c){a.setItem(b,c)}function f(a,b,e){b={value:b,expires:e};d(b)||c.setItem(a,JSON.stringify(b))}function e(a){a=c.getItem(a);try{return a?JSON.parse(a):void 0}catch(b){}}function g(a){a=e(a);var b;return a&&(a.hasOwnProperty("value")&&
a.hasOwnProperty("expires"))&&!d(a)?(b=a.value,delete a.value,[b,a]):[]}function l(a,b,c,d){for(var e,l=0,g=a.length;l<g;l++)e=a.key(l),!c[e]&&(c[e]=e.match(b))&&d(e)}return{set:function(a,c,d){a&&null!=c&&(d=d||{},(null!=d.expires?f:b)(a,c,d.expires))},get:function(b){return a.getItem(b)||g(b)[0]},findEach:function(b,d){var e={};l(a,b,e,function(b){var c=a.getItem(b);null!=c&&d(b,c)});l(c,b,e,function(a){var b=g(a),c=b[0],b=b[1];null!=c&&d(a,c,b)})},remove:function(b){a.removeItem(b);c.removeItem(b)},
purge:function(){for(var a,b,l=c.length;l--;)a=c.key(l),(b=e(a))&&(b.hasOwnProperty("value")&&b.hasOwnProperty("expires"))&&d(b)&&c.removeItem(a)}}}function K(a,c){var d={};d.set=a.set;d.findEach=function(b,d){var e={};a.findEach(b,function(a,b,c){e[a]=!0;d(a,b,c)});c.findEach(b,function(b,c,m){e[b]||(a.set(b,c,m),d(b,c,m))})};d.get=function(b){var d=a.get(b);void 0===d&&(d=c.get(b),void 0!==d&&a.set(b,d));return d};d.remove=function(b){a.remove(b);c.remove(b)};d.purge=function(){a.purge();c.purge()};
return d}function L(a){function c(a){var b={};if(!n.isString(a))return a;r(a.split("&"),function(a){if(""!==a){var c=a.split("=");a=decodeURIComponent(c[0]);c=c[1]&&decodeURIComponent(c[1].replace(/\+/g," "));(null==b[a]?b[a]=[]:b[a]).push(c)}});return b}function d(a,b){var c=[];r(a,function(a){if(n.isObject(a))return!1;a=null==a||""===a?b:a;(n.isString(a)||n.isNumber(a)||n.isBoolean(a))&&c.push(a)});return c}function b(a){return!n.isArray(a)?[a]:a}function f(a,b){var c=encodeURIComponent(a),d=encodeURIComponent(b);
return c+"="+d}var e=this,g={};v(g,c(a));e.param=function(a){a=g[a]||[""];return 1<a.length?a:a[0]};e.params=function(){return g};e.appendParam=function(a,c){if(a){var e=d(b(c));0<e.length&&(g[a]=(null==g[a]?g[a]=[]:g[a]).concat(e))}return this};e.replaceParam=function(a,c){if(a){var e=d(b(c));0<e.length&&(g[a]=(g[a]=[]).concat(e))}return this};e.appendParams=function(a){r(a,e.appendParam);return this};e.alwaysAppendParam=function(a,c){if(a){var e=d(b(c),"");0<e.length&&(g[a]=(null==g[a]?g[a]=[]:
g[a]).concat(e))}return this};e.alwaysReplaceParam=function(a,c){if(a){var e=d(b(c),"");0<e.length&&(g[a]=(g[a]=[]).concat(e))}return this};e.alwaysAppendParams=function(a){r(a,e.alwaysAppendParam);return this};e.appendPartialQueryString=function(a){a&&e.alwaysAppendParams(c(a));return this};e.deleteParam=function(a){delete g[a]};e.toString=function(){var a=[];r(g,function(b,c){r(c,function(c){a.push(f(b,c))})});return a.join("&")}}function E(a){function c(){var a=h.toString();return g+l+(0<a.length?
"?"+a:"")}var d={},b,f,e,g,l,m,k,t,p,h,q=a.match(pa);a=q[1]||"";f=q[2]||"";e=(q[3]||"").substring(1);b=f+(e?":"+e:"");g=a+(b?"//"+b:"");l=q[4]||"";m=(k=l.match(/^(.+?)?\/([^\/]+)?$/))&&k[1]||"";k=k&&k[2]||"";t=(q[5]||"").substring(1);p=(q[6]||"").substring(1);h=new L(t);v(d,h);v(d,{origin:g,scheme:a,host:b,hostname:f,port:e,path:l,pathname:m,scriptname:k,queryString:h.toString,fragment:function(){return p},tooLong:function(){return 2082<c().length},asString:c});d.toString=c;return d}function aa(a,
c,d){function b(){var b=d.createEvent("Event");b.initEvent(c,!0,!1);try{b.currentTarget=b.target=a}catch(e){bt_log("warning: can not set target for ["+c+"] event: "+e)}return b}function f(){var a=d.createEventObject("Event");a.type=c;a.cancelable=!0;a.bubbleable=!1;return a}function e(d){setTimeout(function(){try{(d.handleEvent||d).call(a,g?b():f())}catch(e){bt_log("error: overriding ["+c+"] event: "+e)}},0)}var g=!!a.addEventListener,l=g?"addEventListener":"attachEvent",m=a[l];a[l]=function(b,d,
f){if(d&&("function"==typeof d||"function"==typeof d.handleEvent))if(b==c||b=="on"+c)e(d);else try{g?m.call(a,b,d,f):m(b,d)}catch(l){bt_log("error: proxying ["+b+"] event: "+l)}}}function ba(a,c,d){function b(a){a.hasOwnProperty("enabled")&&(t=a.enabled);a.hasOwnProperty("timestamp")&&(h=a.timestamp,t=!0);a.hasOwnProperty("site")&&(m=a.site);a.hasOwnProperty("referrer")&&(k=a.referrer)}function f(d){d&&b(d);p=[];a.remove(c)}function e(){try{return JSON.stringify({site:m,referrer:k,errors:p})}catch(a){bt_log("problem serializing errors: "+
a.message)}return null}function g(a){var b=n.isObject(a)?v({},a):{};b.type=b.type||"unknown";b.message=b.message||a.toString();b.timestamp=h;return b}function l(){f();p.push(g({type:"runtime",message:"Too many errors"}));a.set(c,e())}if(!a)throw Error("ErrorManager requires a store");var m,k,t=!0,p=[],h=+new Date;d&&b(d);return{configure:b,reset:f,hasErrors:function(){return 0<p.length},tooManyErrors:l,processStoredErrors:function(){var b=a.get(c);if(b)try{var d=JSON.parse(b)||{};m=d.site;k=d.referrer;
n.isArray(d.errors)&&(p=p.concat(d.errors))}catch(e){bt_log("problem reading stored errors: "+e.message)}},push:function(b){bt_log("error: "+JSON.stringify(b));if(t&&b&&!(-1>b.tagId||-1>b.pageId))try{p.push(g(b)),a.set(c,e())}catch(d){if("CookieTooLongError"!=d.name)throw d;l()}},toJSON:e,toArray:function(){return p}}}function qa(a,c){return new function(a,b){function c(a){k.wait(a)}function e(a){function b(){m=h.jQuery;c(a)}l="var $ = BrightTag.$; ";h.jQuery?b():k.script(h.instance.baseUri()+"BrightTag.jquery-1.5.1.js").wait(b)}
var g={},l="",m,k=h.Blab.group(b);g.getJQuery=function(){return m};g.ensureJQuery=function(l){g.ensureJQuery=c;m=a.jQuery;(m?c:e)(l);h.Blab.run(b)};g.functionWithAccess=function(a,b){return new Function(a,l+b)};return g}(a,c)}function ca(a){function c(a,c){c&&c.findEach(a,function(a,c){b.appendParam(a,c)})}function d(a,b){return function(c){bt_log("invalid "+a+" expression: "+b+", exception = "+c)}}var b=this,f=a.window,e=a.parentReferrer,g=a.referrer,l=E(0===a.host.length?"":(/^[a-z0-9+.-]+:\/\/.+/.test(a.host)?
"":"//")+a.host+"/tag");v(b,l);b.toString=l.toString;b.appendParams({site:a.site,referrer:g,docReferrer:a.docReferrer,mode:a.mode,H:U(g||a.document.location.href)});g!==e&&b.appendParam("parentReferrer",e);c(/^btps\..+/,new Q(a.document));c(/^btpdb\..+/,a.store);b.appendData=function(a){var c=bt_data(a),c=n.isArray(c)||n.isObject(c)?f.JSON.stringify(c):c;return b.alwaysReplaceParam("_cb_"+("bt_data('"+a+"')"),c)};b.appendJs=function(a){var c=d("client binding expression",a);return b.alwaysReplaceParam("_cb_"+
a,z(a,c))};b.cf=function(a){n.isArray(a)||(a=[a]);var c=b.param("cf");c&&(a=Array(c).concat(a));b.replaceParam("cf",a.join());return b};b.addCf=function(a,c){if(!z(c,d("conditional fire",c,"tags/"+a+"-cf.js")))return!1;var e=b.param("cf");b.replaceParam("cf",e?e+","+a:a);return!0};var m=b.toString();b.hasConditions=function(){return m!=b.toString()}}function da(a,c){function d(a,b){r(b,function(b,c){a[a.type+"."+b]=c});c.push(a)}function b(a,b,c){var d=h.instance.serverURL();r(a,function(a){a.trigger(b,
c,d)});d.hasConditions()&&h.Blab.script(d.asString())}function f(a,c,e){function g(b,c){r(k,function(g){var f,l=g.name;try{f=h[g.dbe];if(!f){var k=h,p=g.dbe,q,u=g.dbe,n=C("event-dbes/"+l+"-page-"+(B||"adhoc")+"-event-"+a);q=m.functionWithAccess(["eventObject","eventData"],"return "+u+";"+n);f=k[p]=q}e.data(l,f.call(b.target,b,c))}catch(w){d({type:"evdbe",message:w.toString(),pageId:B||-1},{name:l,eventName:a})}})}var f={},k=[],h={},B=(c||{}).pageId;f.data=function(a,b){k.push({name:a,dbe:b});return f};
f.applyDataBindings=g;f.handler=function(c){var d,e=l[a];e&&0<e.length&&(d=Array.prototype.slice.call(arguments,1),g(c,d),b(e,c,d))};return f}function e(a){function b(a){0<k.length&&(a.cf(k),r(h,function(b){a.appendData(b)}),r(D,function(b){a.appendJs(b)}))}function c(a,b){return function(c){bt_log("Invalid "+a+" expression: "+b+", exception = "+c)}}var e={},g={},f,l,k=[],h=[],D=[];e.execute=function(b,c){v(g,c||{});if(n.isFunction(b))l=b;else if(n.isString(b))a:{try{var f=C("events/"+a+"-tag-"+(g.tagId||
"adhoc"));l=m.functionWithAccess(["eventObject","eventData"],b+f);break a}catch(k){d({type:"evparse",message:k.toString(),tagId:g.tagId||-1},{eventName:a})}l=void 0}else bt_log("when.execute: unknown action: "+b);return e};e.evaluate=function(a){f=a;return e};e.fire=function(a){k.push(a);return e};e.appendData=function(a){h.push(a);return e};e.appendJs=function(a){D.push(a);return e};e.trigger=function(e,m,k){var h=c("post-event conditional fire",f);if(!f||z(f,h)){try{l&&l.call(e.target,e,m)}catch(F){d({type:"evwait",
message:F.toString(),tagId:g.tagId||-1},{eventName:a})}b(k)}};return e}var g={},l={},m=qa(a,"BrightTag.jQuery"),k=/^direct\//i;g.executeActions=b;g.Binder=f;g.bind=function(a,b,c,d){var e=f(a,d,h.instance);m.ensureJQuery(function(){var a=m.getJQuery(),d=a(b);if(n.isString(b)&&!k.test(c)&&(d.on||d.live))if(d.on)a(document).on(c,b,e.handler);else d.live(c,e.handler);else d.bind(c.split(k).pop(),e.handler)});return e};g.EventAction=e;g.when=function(a){var b=e(a),c=l[a];c||(c=l[a]=[]);c.push(b);return b};
return g}function ra(a,c,d,b){function f(b,c,e){var g=a.group(e).options(c||{});g.wait(function(){d.process(g,b)})}var e=!1,g={};g[b]=!0;return{tag:function(c,d){var k;k=d&&d.group;k=!e&&!k?b:k;f(c,d,k);k&&void 0===g[k]&&(g[k]=!0,e&&a.run(k))},run:function(){a.addGlobalListener(X(c,d));e=!0;r(g,a.run)}}}function ea(a,c){function d(a){r(n.isArray(a)?a:[a],function(a){n.isFunction(a)?a():p.write('<script type="text/javascript" src="'+a+'">\x3c/script>')})}function b(a){var b=q.group().options({tagId:-2});
r(n.isArray(a)?a:[a],function(a){(n.isFunction(a)?b.wait:b.script)(a)})}function f(a){p.write(a)}function e(a,b){B.tag(a,b)}function g(a){k.writeScript=a?d:b;k.appendContent=a?f:e}function l(a){r(a,function(a){if(a.name){var b=v({},a);delete b.name;delete b.value;u.set(a.name,a.value,b)}})}function m(b){w.hasErrors()&&(b.appendParam("errors",w.toJSON()),b.tooLong()&&(b.deleteParam("errors"),w.tooManyErrors(),b.appendParam("errors",w.toJSON())));w.reset({site:a.site,referrer:a.referrer||p.location.href})}
var k=this,t=a.data||{},p=a.document||{},s=a.window||{},q=a.blab||h.Blab,w=a.errorManager,u=a.store,x=fa(p),B=a.asyncTagManager||ra(q,p,x,"domready");k.referrer=a.referrer;k.parentReferrer=a.parentReferrer;k.docReferrer=a.docReferrer;k.site=a.site;k.host=a.host;k.loadOnly=!!a.loadOnly;w&&q.addGlobalListener(new ga(w));q.run("serializer");k.load=function(){var a=Array.prototype.slice.call(arguments,0);r(a,function(a){n.isFunction(a)?q.addToGroup("serializer",q.newEngine().wait(function(){a(k)})):n.isObject(a)&&
a.src?k.library(a.src,a.options):n.isString(a)&&k.library(a)})};k.library=function(a,b){q.addToGroup("serializer",q.newEngine().options(b||{}).script(a))};g(A(a.mode,"sync"));k.domReady=function(){A(a.mode,"sync")&&g(!1);B.run()};k.parameter=function(a){return window.bt_parameter(a,p)};k.meta=function(a){return window.bt_meta(a,p)};k.cookie=function(a){return window.bt_cookie(a,p)};k.data=function(a,b){if(void 0!==b)return t[a]=b;b=t[a];return null==b?"":b};k.dbe=function(a,b,c){function d(b){w&&
w.push({type:"dbe",message:b.toString(),"dbe.name":a,pageId:(c||{}).pageId||-1})}null==t[a]&&k.data(a,z(b,d,"page-dbes/"+a+"-page-"+(c&&c.pageId||"adhoc")))};k.errors=function(a){w.configure(a)};k.store=u?l:function(){};k.serverURL=function(){return new ca(a)};k.defaultBaseUri=function(){return("https:"==p.location.protocol?"https:":"http:")+"//s.btstatic.com/"};k.baseUri=function(){var a=/\btag(\.[^.]+|-n)?\.js(#.*)?$/;return c&&c.src&&c.src.replace(a,"")||k.defaultBaseUri()};k.primary=function(){function a(){var b=
k.serverURL();w&&(w.processStoredErrors(),m(b));return b.toString()}var b=[];s.JSON?b.push(a()):(b.push(k.baseUri()+"json2.js"),b.push(function(){k.writeScript(a())}));k.writeScript(b)};k.secondary=function(a){var b=k.serverURL(),c=b.toString();a(b);b.toString()!=c&&(w&&m(b),k.writeScript(b.toString()))}}function G(){var a={},c={};return{on:function(c,b){var f=a[c];f||(f=a[c]=[]);f.push(b)},once:function(a,b){var f=c[a];f||(f=c[a]=[]);f.push(b)},emit:function(d){function b(a){a.apply(this,f)}var f=
Array.prototype.slice.call(arguments,1);r(a[d],b);r(c[d],b);c[d]=[]}}}function sa(a){function c(a){return null!=f[a]}function d(a,b){void 0!==b&&(f[a]=b);var c=f[a];return null==c?"":c}var b,f=v({},a);return b=v({dbe:function(a,g,f){if(!c(a)&&(g=z(g,function(c){b.emit("error",c,a,f)}),null!=g))return d(a,g)},data:d,hasData:c},G())}function ta(a){var c,d={},b=["eventObject","eventData","$","bt_data"];return c=v({dbe:function(a,e){try{d[a]=new Function(b,"return "+e+";")}catch(g){g.type="evdbe",c.emit("error",
g,a)}return c},trigger:function(b,e,g){var l=b.target,m=[b,e,g,a.data];r(d,function(b,d){try{a.data(b,d.apply(l,m))}catch(e){e.type="evdbe",c.emit("error",e,b)}})}},G())}function ua(a){function c(a,c){c.type=a;b.emit("error",c)}function d(a){f.push(a);return b}var b,f=[],e=function(){return!0},g=["eventObject","eventData","$","bt_data"];return b=v({fire:function(a){return d(function(b){b.fire(a)})},appendData:function(a){return d(function(b){b.appendData(a)})},appendJs:function(a){return d(function(b){b.appendJs(a)})},
execute:function(e){function f(b,d,e,g){try{p.call(d.target,d,e,g,a.data)}catch(l){c("evwait",l)}}var k;if(n.isString(e))a:{try{k=new Function(g,e);break a}catch(h){c("evparse",h)}k=void 0}else k=e;var p=k;return p?d(f):b},evaluate:function(c){var d=new Function(g,"return "+c);e=function(b,c,e,g){return d.call(c.target,c,e,g,a.data)};return b},trigger:function(a,b,c,d){e(a,b,c,d)&&r(f,function(e){e(a,b,c,d)})}},G())}function va(a){var c=/^direct\//i,d=!1;return{bind:function(a,d,e){function g(a){var b=
Array.prototype.slice.call(arguments,1);e(a,b,h.jQuery||window.jQuery)}var l=h.jQuery||window.jQuery,m=l(a),k=c.test(d);if(!k&&m.on)l(document).on(d,a,g);else!k&&m.live?m.live(d,g):m.bind(d.split(c).pop(),g)},newBinder:function(a){return ta(a)},newHandler:function(a){return ua(a)},ensureLibrary:function(b){h.jQuery||window.jQuery?b():(d||(d=!0,a.run()),a.wait(b))}}}function wa(a,c){function d(b,c,d,h){var k=R(a);r(b,function(a){a.trigger(k,c,d,h)});f.emit("triggered",k)}var b={},f=G();return v(f,
{bind:function(e,g,l,h){function k(a,c,g){t.trigger(a,c,g);d(b[e],a,c,g)}var t=c.newBinder(a,e);t.on("error",function(a,b){f.emit("error",a,{name:b,eventName:e},h)});c.ensureLibrary(function(){c.bind(g,l,k)});return t},handle:function(d,g){var l=c.newHandler(a);l.on("error",function(a){f.emit("error",a,{eventName:d},g)});b[d]=b[d]||[];b[d].push(l);return l}})}function fa(a){function c(a,b){a.src?b.preemptScript(a.src,a.innerHTML):a.innerHTML&&b.preemptWait(a.innerHTML)}function d(b){try{a.body.appendChild(b.cloneNode(!0))}catch(c){bt_log("error appending content to body: "+
c)}}var b=a.createElement("div");return{process:function(a,e){if(0!==e.length){b.innerHTML="<br/>"+e;for(var g=b.childNodes||[],l=1,h=g.length;l<h;l++)("SCRIPT"==g[l].tagName?c:d)(g[l],a)}}}}function xa(a){function c(b){a.write(b);return d}var d={tag:c,script:function(a){return c('<script type="text/javascript" src="'+a+'">\x3c/script>')},wait:function(a){a();return d}};return d}function ya(a,c){function d(c,d){var f=c&&c.group;d(a.group(f).options(c||{}));f&&void 0===b[f]&&(b[f]=!0,a.run(f))}var b=
{},f={tag:function(a,b){d(b,function(b){b.wait(function(){c.process(b,a)})});return f},script:a.script,wait:a.wait};return f}function za(a,c){var d=c;return{tag:function(a,c){return d.tag(a,c)},script:function(a){return d.script(a)},wait:function(a){return d.wait(a)},sync:function(){d=a},async:function(){d=c}}}function ga(a){return{dbe:function(c,d,b){a.push({type:"dbe",message:c.toString(),"dbe.name":d,pageId:(b||{}).pageId||-1})},events:function(c,d,b){var f=c.type,e="evdbe"===f?"pageId":"tagId",
g={type:f,message:c.toString()};r(d,function(a,b){g[f+"."+a]=b});g[e]=(b||{})[e]||-1;a.push(g)},"block:error":function(c,d){var b,f,e;d&&(b=d.type,f=d.exception||d,e=c.option("tagId")||-1,a.push({type:b,message:f.toString(),tagId:e}))}}}function Aa(a){function c(){var b=new E(a.src),c={},d=b.fragment();c.staticHost=b.host+b.pathname;d&&r((new L(d)).params(),function(a,b){c[a]=1<b.length?b:b[0]});return c}function d(){var b=x(a.innerHTML);return 0===b.length?{}:z("(\n"+b+"\n)",function(a){bt_log("json configuration error: "+
a)})}return{isTagjs:function(){return/\/tag(\.[^.]+|-n)?\.js(\?.*)?(#.*)?$/.test(a.src)},toJSON:function(){return v(c(),d())},script:a}}function Ba(a){return{isTagjs:function(){return!0},toJSON:function(){return a||{}},script:{src:void 0}}}function ha(){function a(){return c}var c;return c={fire:a,appendData:a,appendJs:a,execute:a,when:a}}function R(a){function c(a,b){for(var c in a)if(b(c,a[c]))return!0;return!1}var d,b=[],f={};return d={toJSON:function(){var a=0<b.length?{cf:b.join()}:{};return v(a,
f)},fire:function(a){a=S(a,function(a){return null!=a&&""!==a});b=b.concat(a);return d},appendData:function(b){f["_cb_bt_data('"+b+"')"]=a.data(b);return d},appendJs:function(a){f["_cb_"+a]=z(a);return d},execute:function(a){a();return d},when:function(b){var c;try{return c=new Function(["bt_data"],"return "+h.trim(b)),c(a.data)?d:ha()}catch(f){bt_log("conditional evaluation error: ["+f.toString()+"] while evaluating ["+b+"]")}return ha()},hasConditions:function(){return 0<b.length||c(f,function(a,
b){return null!=b})}}}function Ca(a,c,d,b,f,e){function g(){s=!0;c.async();q.mode=y.filter(q.mode,function(a){return"sync"!==a})}function h(a){null==window.JSON?c.script(E(q.staticHost+"/json2.js")).wait(a):a()}function m(a){if(null==a||a.hasConditions())b.reset({site:q.site,referrer:q.referrer||window.location.href})}function k(a){var c=E("//"+r+"/tag").appendParams({site:q.site,mode:q.mode,H:q.H,referrer:q.referrer,docReferrer:q.docReferrer}).alwaysAppendParams(a);f.findEach(RegExp("^btp(s|db)\\."+
q.site+"\\..+"),function(a,b){c.appendParam(a,b)});return c.appendParams({errors:b.hasErrors()?b.toJSON():null})}function t(a){if(null==a)return k();if(a.hasConditions())return k(a.toJSON())}function p(a){var d=t(a);d?(d.tooLong()&&(b.tooManyErrors(),d=t(a)),m(a),c.script(d.toString())):m(a)}var n,q=y.extend({},e),r=q.host||"",u=G(),s=!1;d.on("triggered",p);return n=y.extend({config:q,diagnostic:function(a){a&&(q.diagnostic=a,n.emit("diagnostic",a))},errors:function(a){b.configure({timestamp:a})},
dbe:function(b,c,d){var e=a.dbe(b,c,d);null!=e&&n.emit("dbe",b,c,e,d)},data:a.data,dataref:function(a){return null==a?"":'BrightTag.site("'+q.site+'").data("'+a.replace(/"/g,"\\x22")+'")'},store:function(a){y.each(a,function(a){if(a.name){var b=y.extend({},a);delete b.name;delete b.value;f.set(a.name,a.value,b)}})},tag:function(a,b){n.emit("tag",a,b);return c.tag(a,b)},script:c.script,wait:c.wait,events:{bind:function(a,b,c,e){n.emit("event-binding",a,b,c,e);return d.bind(a,b,c,e)},on:d.handle},when:function(b,
c){R(a).when(b).execute(function(){c(n)});return n},domready:function(a){if(null==a)g();else u.once("domready",a);s&&u.emit("domready",n)},primary:function(){h(function(){b.processStoredErrors();p()})},secondary:function(b){var c=R(a);b(c);p(c)}},G())}function Da(a){a=E(a.staticHost+"/BrightTag.jquery-1.5.1.js");return va((new V(document)).script(a))}function Ea(a,c,d){var b=xa(document);a=ya(a,c);b=za(b,a);y.contains(d.mode,"sync")&&b.sync();return b}function Fa(a){var c,d,b,f,e,g,l,m;if((l=a.site)&&
!M[l])return c=sa(a.data),d=new Y(document),m=fa(document),b=Ea(d,m,a),e=wa(c,Da(a)),g=ba(H?K(H,N):N,"__bterr_"+l,{enabled:!1}),f=ga(g),c.on("error",f.dbe),e.on("error",f.events),d.addGlobalListener(f),h.Events.onDOMReady(function(){d.addGlobalListener(X(document,m))}),a=M[l]=Ca(c,b,e,g,H?K(N,H):N,a)}function ia(a,c,d){try{var b,f,e=a.toJSON();if(!(h.instance&&h.instance.site===e.site)){var g=v({host:"s.thebrighttag.com",staticHost:"s.btstatic.com",H:U(e.referrer||c.location.href),docReferrer:c.document.referrer},
e);b=Fa(g);if(e.site&&!h.instance&&!ja&&!A(e.mode,"v2")&&!A(e.mode,"v2b")){var l=a.script,m=ka();h.EventBinding=da(m.window,m.errorManager);h.instance=new ea(v(m,e),l);f=h.instance;b.config.loadOnly=!0}else if(b){var k=b.config,n;var p=b.config.mode;n=A(p,"v2")?p:!p?"v2":["v2"].concat(p);k.mode=n}d&&d(b,f);return b}}catch(r){bt_log("error configuring site ["+a.script.src+"]: "+r)}}function Ga(a){var c,d,b=[];if(n.isArray(a))b=a.slice(0);else{c=0;for(d=a.length;c<d;c++)b.push(a[c])}return b}function Ha(a){if(!ja&&
!A(a.config.mode,"v2")&&!A(a.config.mode,"v2b"))h.Events.onDOMReady(function(c){a.domready()});else a.config.loadOnly||(h.Events.onDOMReady(function(c){a.domready()}),a.primary())}function ka(){var a,c=Z(document),d=c,b=c;try{window.localStorage&&window.sessionStorage&&(a=$(sessionStorage,localStorage),a.purge(),d=K(c,a),b=K(a,c))}catch(f){bt_log("Unable to access DOM storage: "+f)}return{id:Math.random(),loadOnly:!1,window:window,document:document,host:"s.thebrighttag.com",parentReferrer:top!=self&&
self.window?self.window.location.href:null,docReferrer:document.referrer,data:{},store:d,errorManager:ba(b,"__bterr")}}if(h)return h;var ja=!1;h={};var n={isString:function(a){return s(a,"String")},isArray:function(a){return s(a,"Array")},isNumber:function(a){return s(a,"Number")},isBoolean:function(a){return s(a,"Boolean")},isFunction:function(a){return s(a,"Function")},isObject:function(a){return null===a||void 0===a?!1:s(a,"Object")}},z=bt_eval,O=Array.prototype.forEach?Array.prototype.forEach:
I,ma=Array.prototype.filter?Array.prototype.filter:la,Ia=Array.prototype.map?Array.prototype.map:na,y={contains:A,each:r,extend:v,filter:S,map:function(a,c,d){return Ia.call(n.isArray(a)?a:[a],c,d)},trim:x},oa=function(){function a(){}function c(a,b,c){try{a[b]=c}catch(d){bt_log("warning: could not assign value to 'document."+b+"': "+d)}}var d,b=[],f=function(a){d.push(a)};return function(e,g){var h;this["block:start"]=function(){b.push([d,e.write,e.writeln,e.open,e.close]);d=[];c(e,"write",f);c(e,
"writeln",f);c(e,"open",a);c(e,"close",a)};this["block:finish"]=function(){try{g.process(h,d.join(""))}finally{var a=b.pop();d=a[0];c(e,"write",a[1]);c(e,"writeln",a[2]);c(e,"open",a[3]);c(e,"close",a[4])}};this["engine:listen"]=function(a){h=a}}}(),pa=/^(?:([^:\/]+:)?\/\/)?([^:\/?#]+)?(:[0-9]+)?([^?#]*)(\?[^#]*)?(#.*)?$/,M={},H,N=Z(document);try{window.localStorage&&window.sessionStorage&&(H=$(sessionStorage,localStorage),H.purge())}catch(Ja){bt_log("Unable to access DOM storage: "+Ja)}h.Escaper=
{cookie:T,javascript:function(a){return!n.isString(a)?a:a.replace(/\\/g,"\\\\").replace(/'/g,"\\x27").replace(/"/g,"\\x22").replace(/\n/g,"\\n").replace(/\r/g,"\\r")}};h.Random={integer:function(a){return Math.floor(Math.random()*(a||1E8))}};h.pushIfDefined=function(a,c,d){a&&(a.constructor==Array&&null!=c)&&a.push(d||c)};h.ServerURL=ca;h.Main=function(a){function c(b){(b=(new E(b.src)).fragment())&&r((new L(b)).params(),function(b,c){a[b]=c[0]})}function d(b){function c(a){bt_log("configuration error: "+
a)}b=x(b.innerHTML);0!==b.length&&v(a,z("(\n"+b+"\n)",c,"site-config"))}var b,f=function(){var b,c,d=/\/tag(\.[^.]+|-n)?\.js(#.*)?$/,e=a.document.getElementsByTagName("script");for(b=e.length-1;-1<b;b--)if(c=e[b],d.test(c.src))return c}();f&&(c(f),d(f));if(null!=a.site){h.Events.enablePageReadyOverrides();try{b=new ea(a,f),h.Events.onDOMReady(b.domReady),b.loadOnly||b.primary()}catch(e){bt_log("execution error: "+e)}return b}};h.CookieSync={pushImage:function(a){(new Image).src=a;throw"CookieSync.pushImage no longer supported ["+
a+"]";},pushIframe:function(a){throw"CookieSync.pushIframe no longer supported ["+a+"]";}};h.EventBindingManager=da;h.defaultConfig=ka;h.eval=z;h.Types=n;h.trim=y.trim;h.Util=y;h.each=y.each;h.extend=y.extend;h.HTTP={Cookie:Q,QueryString:L,URL:E};h.Blab=new Y(document);h.Events=new function(a,c){function d(){}function b(a,b,c){a[q](u+b,c,!1)}function f(a,b,c){a[s](u+b,c,!1)}function e(){var a=c.readyState;if("loading"==a)return!1;if("complete"==a)return!0;a:{try{v("left")}catch(b){a=!1;break a}a=
!0}return a}function g(a,b,c){var d=this;setTimeout(function(){a()?b.call(d):g(a,b,c)},c)}function h(){h=d;n&&aa(c,p,c)}function m(){h();aa(a,r,c)}var k=this,n=!!a.addEventListener,p="DOMContentLoaded",r="load",q=n?"addEventListener":"attachEvent",s=n?"removeEventListener":"detachEvent",u=n?"":"on",v=c.documentElement.doScroll||function(){throw"No doScroll";};k.listen=b;k.unlisten=f;k.onDOMReady=function(d){e()?d.call(this):c.addEventListener?(b(c,p,d),b(c,p,function(){f(a,r,d)}),b(a,r,d)):g(e,d,
1)};k.enablePageReadyOverrides=function(){k.enablePageReadyOverrides=d;e()?m():(n&&b(c,p,h),b(a,r,m))}}(window,document);h.Events.enablePageReadyOverrides();h.Content=new function(a){a=a||h.Blab;return{iframe:a.iframe,image:a.image,link:a.link,script:a.script}}(h.Blab);h.site=function(a,c){try{var d=M[a];d&&c&&c(d);return d}catch(b){bt_log("error while executing site configuration ["+a+"]: "+b)}};h.configureNewSites=function(a,c){r(Ga(a.document.getElementsByTagName("script")),function(d){d=Aa(d);
d.isTagjs()&&ia(d,a,c)})};h.configureSite=function(a,c,d){return ia(Ba(a),c,d)};h.configuredSites=function(){var a=[];y.each(M,function(c,d){a.push(d)});return a};h.initializeSite=function(a,c){c&&(h.Events.onDOMReady(c.domReady),c.loadOnly||c.primary());a&&Ha(a)};return h}(window.BrightTag);(function(h){h.configureNewSites(window,h.initializeSite);null==h.instance&&setTimeout(function(){null==h.instance&&h.configureNewSites(window,h.initializeSite)},0)})(BrightTag);
var _bt_url_prefix,_bt_referrer,_bt_site,_bt_mode;function btServe(h){var s=BrightTag,x={referrer:_bt_referrer,site:_bt_site,mode:_bt_mode};null!=_bt_url_prefix&&(x.host=_bt_url_prefix);s.configureSite(s.extend(x,h),window,s.initializeSite)};
